### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by UrielMiranda** [AlexZ-25/AlexZ-25.github.io#1]
<img width="668" alt="Screen Shot 2022-04-28 at 9 36 12 PM" src="https://user-images.githubusercontent.com/12901838/165873031-d0448084-c80a-47e9-9ec8-2be52b8d0159.png">

Darle un poco de espacio a la derecha al formulario, ayudari a ubicarlo de una mejor manera, ya que de esta manera da la percepcion de que falta algo y dar scroll.

Otro punto que podria ayudarte, es utilizar, etiquetas semanticas, por ejemplo el <header></header>, hay etiqueta para header
otra como <main></main>

**Comment by AlexZ-25** [comment]
Hola Uriel - Muchas gracias por tu feedback, creo que el final del mensaje no se envió completo, no veo la etiqueta de ejemplo.

**Comment by UrielMiranda** [comment]
```html
<header></header>
<main></main>
<footer><footer>
````
esas 2 serian buenas

**Comment by AlexZ-25** [comment]
Excelente, muchas gracias por la información. Ya las agregué.
